.github/workflows/ml-kem.yml
.github/workflows/workspace.yml
Cargo.toml
ml-kem/Cargo.toml
ml-kem/src/kem.rs
ml-kem/src/lib.rs

NOTE: the tests aren't passing for me locally, so I expect this won't build
cc @bifurcation

ml-kem: add initial CI configuration

---

ml-kem/Cargo.toml
ml-kem/LICENSE-APACHE
ml-kem/LICENSE-MIT

These are the standard licenses we use for all @RustCrypto projects.
cc @bifurcation

ml-kem: license as Apache 2.0 + MIT

---

ml-kem/Cargo.toml
ml-kem/README.md
ml-kem/src/lib.rs

Uses the standard README.md template we use for all RustCrypto projects

ml-kem: add README.md

---

Cargo.lock
ml-kem/CHANGELOG.md
ml-kem/Cargo.toml
ml-kem/README.md

Initial release.
Only change from `v0.1.0-alpha` is bumping `hybrid-array` to `v0.2.0-rc.8`.

ml-kem v0.1.0

---

.github/workflows/ml-kem.yml
Cargo.lock
ml-kem/Cargo.toml
ml-kem/src/kem.rs
ml-kem/src/lib.rs
ml-kem/tests/vectors.rs

updates ml-kem as advertised. this keeps EncapsulateDeterministic inside ml-kem though, perhaps this trait also deserves promotion to kem?

implement Decapsulate and Encapsulate from traits/kem

---

.github/workflows/ml-kem.yml
Cargo.lock
ml-kem/Cargo.toml
ml-kem/benches/mlkem.rs

Some late changes in #2 appear to have broken the benchmarking code.  This PR makes the few small changes needed to get it working again.

ml-kem: fix benchmarking code

---

.github/workflows/ml-kem.yml
Cargo.lock
ml-kem/Cargo.toml
ml-kem/benches/mlkem.rs

This reverts commit bcfd143df58d64a4ff71e1d8ab7908c02e7d93eb.

Revert "Add support for Codspeed performance testing (#20)"

---

.github/workflows/workspace.yml
Cargo.lock
ml-kem/Cargo.toml
ml-kem/src/algebra.rs
ml-kem/src/compress.rs
ml-kem/src/encode.rs
ml-kem/src/lib.rs
ml-kem/src/param.rs

Updates the `compress` method to remove division of secret values by public value (q) as described in the [kyberslash attack](https://kyberslash.cr.yp.to/index.html)
Also updates tests to use inequality as per 4.7 in [FIPS 203 draft](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.203.ipd.pdf) to not use floating point arithmetic.

ml-kem: fix potential kyberslash attack

---

.github/workflows/workspace.yml

Previously `beta` was used for the `integer_division_remainder_used` lint, which was stabilized in 1.79 which was released today.
Closes #27

CI: run `clippy` on 1.79 stable

---

ml-kem/src/crypto.rs
ml-kem/tests/vectors.rs

Resolves failing workspace action due to newly deprecated method in `hybrid-array` giving clippy warnings in #33.
Uses expect as these are only tests and no need for fully fleshed out error handling.

Updates tests to use `try_from` instead of deprecated `from_slice`

---

.github/workflows/dhkem.yml
Cargo.lock
Cargo.toml
dhkem/Cargo.toml
dhkem/src/arithmetic.rs
dhkem/src/hpke_p256_test.rs
dhkem/src/lib.rs
dhkem/src/tests.rs
dhkem/src/x25519_kem.rs

This replaces RustCrypto/traits#1556 and puts the `Encapsulate` and `Decapsulate` implementations into their own newtype. It probably needs some actual documentation at some point as well.
As an extension, maybe the `DhKem` trait should be promoted `traits/kem` as `KEM`, as `KeyGen() -> (PrivateKey, PublicKey)` is also part of the standard KEM model and provides a central trait for `impl<k1, k2> KEM for TlsKemCombiner<k1, k2> where k1, k2: KEM`. That way, we can just write `type X25519Kyber768Draft00 = TlsKemCombiner<dhkem::X25519, MlKem768>` once the `ml-kem` crate gets updated.

Add KEM providers for common ECDH schemes

---

.github/workflows/dhkem.yml
.github/workflows/ml-kem.yml
Cargo.lock
dhkem/Cargo.toml
dhkem/src/arithmetic.rs
dhkem/src/lib.rs
dhkem/tests/hpke_p256_test.rs
dhkem/tests/tests.rs

Adds `no_std` support to `dhkem`, which involved moving `std`-dependent tests from `lib/` to the `tests/` directory, which links them in a separate crate that can access `std`.
Also adds `default-features = false` to each of the elliptic curve crate dependencies.
Finally, adds a CI check that the crate can link on a `no_std` target.

dhkem: add `no_std` + refactor tests

---

Cargo.lock
dhkem/Cargo.toml
dhkem/src/ecdh_kem.rs
dhkem/src/lib.rs
dhkem/src/x25519_kem.rs
dhkem/tests/hpke_p256_test.rs
dhkem/tests/tests.rs

Also adds `#[warn(missing_docs)]`.
This reduces the curve choices to the following:
- k256: secp256k1
- p256: NIST P-256
- p384: NIST P-384
- p521: NIST P-521
It also adds `*Kem` to the end of every type name, to avoid a name clash between elliptic curves and their respective KEMs.

dhkem: fewer curve choices, add `*Kem` to type names

---

ml-kem/src/kem.rs

ml-kem: make `DecapsulationKey::encapsulation_key` a `pub fn`

---

ml-kem/src/kem.rs
ml-kem/src/lib.rs

- Re-exports `kem::{Decapsulate, Encapsulate}` under `kem` module
- Re-exports `hybrid-array` as `array`
Closes #36

ml-kem: re-export `kem` traits and `hybrid-array`

---

Cargo.lock
ml-kem/CHANGELOG.md
ml-kem/Cargo.toml

- `DecapsulationKey::encapsulation_key` ([#48])
- Re-export `kem::{Decapsulate, Encapsulate}` under `kem` module ([#49])
- Re-exports `hybrid-array` as `array` ([#49])
- Update to FIPS 203 final ([#47])
[#47]: https://github.com/RustCrypto/KEMs/pull/47
[#48]: https://github.com/RustCrypto/KEMs/pull/48
[#49]: https://github.com/RustCrypto/KEMs/pull/49

ml-kem v0.2.0

---

Cargo.lock
ml-kem/Cargo.toml
ml-kem/src/algebra.rs
ml-kem/src/kem.rs
ml-kem/src/pke.rs

I'm not totally sure I understand the `zeroize` crate and its sharp edges, but I think this implements zeroization correctly.  Basically just starts at `kem::DecapsulationKey` and works down the stack from there.

ml_kem: Enable zeroization

---

Cargo.lock
ml-kem/CHANGELOG.md
ml-kem/Cargo.toml

- `zeroize` feature ([#51])
[#51]: https://github.com/RustCrypto/KEMs/pull/51

ml-kem v0.2.1

---

.github/workflows/ml-kem.yml
ml-kem/benches/mlkem.rs

Benches weren't compiling. They were using non-public deterministic functions. Now they use the random functions. Also I removed key parsing from the encap and decap functions. IMO they should just be doing encap/decap, but I can add ser/deser back in if you think it really belongs there.

Fixed ML-KEM benches

---

.github/workflows/workspace.yml

Avoids building documentation for dependencies.
Should improve build times.

CI: doc with `--no-deps`

---

Cargo.lock
ml-kem/Cargo.toml
x-wing/Cargo.toml

There were breaking changes in #59.
This denotes that a breaking change occurred, however there won't be a release associated with this commit. Instead we'll release a `pre.0` or a v0.3.0 final.

ml-kem: bump to v0.3.0-pre

---

.github/workflows/frodo-kem.yml

This follows the configuration of the other crates in the repo

CI: always build `frodo-kem` on push

---

frodo-kem/Cargo.toml
frodo-kem/README.md

- Corrects old links to `frodo-kem-rs` to use new `frodo-kem` name
- Bumps the package version to `0.0.0` since it hasn't been released
- Groups Cargo.toml closer to our other packages

frodo-kem: metadata cleanups

---

.github/workflows/workspace.yml
dhkem/tests/hpke_p256_test.rs
frodo-kem/benches/frodo.rs
frodo-kem/benches/safe_oqs.rs
frodo-kem/src/hazmat.rs
frodo-kem/src/lib.rs
ml-kem/src/algebra.rs
ml-kem/src/compress.rs
ml-kem/src/encode.rs
x-wing/src/lib.rs

Notably this also runs clippy on test cases.
For now the violations which couldn't be fixed automatically with `--fix` have been annotated with `allow`, but in the future the code could be improved.

clippy: enable `--all-targets`

---

.github/workflows/frodo-kem.yml
frodo-kem/Cargo.toml

We previously weren't testing on MSRV.
This uses `set-msrv` + a CI matrix with `stable` to do that, which also clears the way towards running `cross`

frodo-kem: use `set-msrv` in CI

---

x-wing/src/lib.rs

This is the most conservative choice for a random number generator for keygen, which is a thin wrapper for the `getrandom` crate, which gets randomness directly from the OS.
Also removes superfluous newlines in the example, and makes the imported traits explicit so the code example is complete.

x-wing: use `rand::rngs::OsRng` in code example

---

x-wing/src/lib.rs

Noticed I made a mistake in the way the ECC ephemeral keys are created:
```
let ek_x: SharedSecret = generate(rng);
let ct_x = x25519(ek_x, X25519_BASEPOINT_BYTES);
```
This result may not always be correct as no clamping is done on the generated `ek_x`.

x-wing: correct usage of ECC
